# IBM Developer's Workframe/2 Make File Creation run at 15:57:50 on 11/30/92

# Make File Creation run in directory:
#   E:\QUANT\GIFLIB;

# Assumed INCLUDE environment variable path:
#   E:\TOOLKT20\C\OS2H;
#   E:\IBMC\INCLUDE;


DGIF_LIB.OBJ:  DGIF_LIB.C  \
#  {$(INCLUDE);}stdlib.h  \
#  {$(INCLUDE);}io.h  \
#  {$(INCLUDE);}alloc.h  \
#  {$(INCLUDE);}sys\stat.h  \
#  {$(INCLUDE);}fcntl.h  \
#  {$(INCLUDE);}string.h  \
   {.;$(INCLUDE);}gif_lib.h  \
#    {$(INCLUDE);}stdio.h  \
   {.;$(INCLUDE);}gif_hash.h  \
   MAKEFILE

EGIF_LIB.OBJ:  EGIF_LIB.C  \
#  {$(INCLUDE);}string.h  \
#  {$(INCLUDE);}alloc.h  \
   {.;$(INCLUDE);}gif_lib.h  \
#    {$(INCLUDE);}stdio.h  \
   {.;$(INCLUDE);}gif_hash.h  \
   MAKEFILE

GIF_HASH.OBJ:  GIF_HASH.C  \
#  {$(INCLUDE);}mem.h  \
   {.;$(INCLUDE);}gif_hash.h  \
   MAKEFILE
